# Generated by Django 5.2.7 on 2025-10-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('func', 'Funcionário'), ('prof', 'Professor'), ('aluno', 'Aluno')], default='aluno', help_text='Papel do usuário dentro do sistema.', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='Breve descrição do usuário (opcional).', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('sala', 'Sala'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_uso', 'Em uso')], default='ativo', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='app_environ_name_54783d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom'), ('manutencao', 'Em manutenção'), ('defeito', 'Com defeito')], default='bom', max_length=20)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='app.environment')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['serial_number'], name='app_equipme_serial__a56a74_idx'), models.Index(fields=['name'], name='app_equipme_name_b46b37_idx')],
            },
        ),
    ]
