# Generated by Django 5.2.7 on 2025-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_environment_ativo_environment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
